name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: rapport-example.tex
          latexmk_shell_escape: true
      - name: Commit files  
        run:
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add rapport-example.pdf
          git commit -m "add generated pdf $(date)"
          git push -f origin main
          
